name: maxi_library_db_mysql
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  reflectable: ^4.0.9
  mysql_client: ^0.0.27
  meta: ^1.15.0
  # path: ^1.8.0

  maxi_library:
  #git:
    #  url: https://github.com/MaxiCamilo/maxi_library.git
    #  ref: main
    path: ../maxi_library

  maxi_library_db:
  #git:
    #  url: https://github.com/MaxiCamilo/maxi_library_db.git
    #  ref: main
    path: ../maxi_library_db

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
